import { Product } from "@/types/products";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "p-101",
    title: "Handcrafted Celestial Harmony Canvas Art",
    subtitle: "Original Textured Oil Painting with Gold Leaf Accents",
    category: "Wall Art & Canvas",
    price: 290.0,
    originalPrice: 350.0,
    rating: 4.9,
    reviewCount: 48,
    stock: 12,
    sku: "ART-CEL-2436",
    description: `Immerse your space in the ethereal beauty of Celestial Harmony. Hand-painted by master artist Tahleel Studio using layered impasto oil techniques and genuine 24K gold leaf leafing. 
    
    Each piece is individually gallery-wrapped on sustainable kiln-dried pine wood stretchers, ready to hang. Features deep tactile textures that catch light beautifully throughout the day.`,
    vendorName: "Tahleel Studio",
    vendorPhone: "+15552345678",
    vendorEmail: "studio@altrio.com",
    vendorLocation: "San Francisco, CA",
    shippingInfo: "Free Express Shipping on orders over $150. Packaged in custom reinforced wooden crates.",
    returnPolicy: "30-Day Risk-Free Guarantee. Free returns and full refunds if not delighted.",
    media: [
      {
        id: "m1",
        type: "image",
        url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
        thumbnail: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=200&q=80",
        alt: "Celestial Harmony Main Artwork Display",
      },
      {
        id: "m2",
        type: "image",
        url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
        thumbnail: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=200&q=80",
        alt: "Close-up Gold Leaf Texture Detail",
      },
      {
        id: "m3",
        type: "video",
        url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        thumbnail: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=200&q=80",
        alt: "Video Showcase & Artist Studio Tour",
      },
    ],
    variants: [
      {
        id: "v-2436-oak",
        name: "24 x 36 Inches / Natural Oak Frame",
        size: "24 x 36 Inches",
        color: "Natural Oak Frame",
        price: 290.0,
        originalPrice: 350.0,
        stock: 12,
        sku: "ART-CEL-2436-OAK",
        image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
      },
      {
        id: "v-3648-oak",
        name: "36 x 48 Inches / Natural Oak Frame",
        size: "36 x 48 Inches",
        color: "Natural Oak Frame",
        price: 420.0,
        originalPrice: 490.0,
        stock: 5,
        sku: "ART-CEL-3648-OAK",
        image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    specs: [
      { label: "Medium", value: "Impasto Oil & 24K Gold Leaf on Canvas" },
      { label: "Frame Material", value: "FSC-Certified Solid Kiln-Dried Oak" },
      { label: "Dimensions", value: "24\" W x 36\" H x 1.5\" D" },
    ],
    reviews: [
      {
        id: "r1",
        author: "Eleanor Vance",
        rating: 5,
        date: "August 2, 2026",
        comment: "Absolutely breathtaking piece! The gold leaf texture sparkles under warm evening light.",
        verifiedPurchase: true,
      },
    ],
    relatedProducts: [
      {
        id: "p-102",
        title: "Sculpted Earthenware Ceramic Vessel",
        category: "Ceramics & Sculpture",
        price: 165.0,
        originalPrice: 195.0,
        image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=600&q=80",
        rating: 4.8,
      },
    ],
  },
  {
    id: "p-102",
    title: "Sculpted Earthenware Ceramic Vessel",
    subtitle: "Artisanal Terracotta Vase with Matte Chalk Finish",
    category: "Ceramics & Sculpture",
    price: 165.0,
    originalPrice: 195.0,
    rating: 4.8,
    reviewCount: 32,
    stock: 8,
    sku: "CER-VES-0165",
    description: "Wheel-thrown terracotta ceramic vessel crafted with natural raw earth pigments and a smooth chalky matte glaze.",
    vendorName: "Tahleel Studio",
    vendorPhone: "+15552345678",
    vendorEmail: "studio@altrio.com",
    vendorLocation: "San Francisco, CA",
    shippingInfo: "Padded in bio-degradable foam packaging.",
    returnPolicy: "30-Day Easy Returns.",
    media: [
      {
        id: "m1",
        type: "image",
        url: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1200&q=80",
        thumbnail: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=200&q=80",
        alt: "Ceramic Vessel Display",
      },
    ],
    variants: [
      {
        id: "v-terracotta",
        name: "Medium (14\" High) / Terracotta Raw",
        size: "Medium 14\"",
        color: "Terracotta Raw",
        price: 165.0,
        stock: 8,
        sku: "CER-VES-MED-TER",
      },
      {
        id: "v-chalkwhite",
        name: "Large (18\" High) / Chalk White Glaze",
        size: "Large 18\"",
        color: "Chalk White",
        price: 210.0,
        stock: 3,
        sku: "CER-VES-LRG-WHT",
      },
    ],
    specs: [
      { label: "Material", value: "Natural Terracotta Clay" },
      { label: "Dimensions", value: "8\" Diameter x 14\" Height" },
    ],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: "p-103",
    title: "Nordic Minimalist Wood Wall Clock",
    subtitle: "Silent Sweep Quartz Movement with Solid Walnut Dial",
    category: "Home Accent",
    price: 120.0,
    originalPrice: 145.0,
    rating: 4.9,
    reviewCount: 64,
    stock: 15,
    sku: "CLK-MIN-0120",
    description: "Sleek scandinavian minimalist clock carved from solid American Walnut with brushed brass hands.",
    vendorName: "Tahleel Studio",
    vendorPhone: "+15552345678",
    vendorEmail: "studio@altrio.com",
    vendorLocation: "San Francisco, CA",
    shippingInfo: "Ships within 24 hours.",
    returnPolicy: "30-Day Money-Back Guarantee.",
    media: [
      {
        id: "m1",
        type: "image",
        url: "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=1200&q=80",
        thumbnail: "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=200&q=80",
        alt: "Nordic Wall Clock Display",
      },
    ],
    variants: [
      {
        id: "v-walnut-12",
        name: "12 Inches Diameter / Solid Walnut",
        size: "12 Inches",
        color: "Solid Walnut",
        price: 120.0,
        stock: 15,
        sku: "CLK-WAL-12",
      },
      {
        id: "v-oak-16",
        name: "16 Inches Diameter / Natural Oak",
        size: "16 Inches",
        color: "Natural Oak",
        price: 155.0,
        stock: 6,
        sku: "CLK-OAK-16",
      },
    ],
    specs: [
      { label: "Movement", value: "Silent Sweep Non-Ticking Quartz" },
      { label: "Battery", value: "1x AA Battery Required (Included)" },
    ],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: "p-104",
    title: "Botanical Shadowbox Framed Print Set",
    subtitle: "Set of 3 Archival Giclée Fern & Palm Studies",
    category: "Framed Prints",
    price: 110.0,
    originalPrice: 135.0,
    rating: 4.7,
    reviewCount: 29,
    stock: 2,
    sku: "PRN-BOT-0110",
    description: "Botanical illustration trilogy printed on 300gsm cotton rag archival paper with glass shadowbox framing.",
    vendorName: "Tahleel Studio",
    vendorPhone: "+15552345678",
    vendorEmail: "studio@altrio.com",
    vendorLocation: "San Francisco, CA",
    shippingInfo: "Insured glass packaging.",
    returnPolicy: "30-Day Returns.",
    media: [
      {
        id: "m1",
        type: "image",
        url: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80",
        thumbnail: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=200&q=80",
        alt: "Botanical Shadowbox Print Set",
      },
    ],
    variants: [
      {
        id: "v-set3-oak",
        name: "Set of 3 (12x16\" each) / Oak Shadowbox",
        size: "Set of 3 (12x16\")",
        color: "Oak Shadowbox",
        price: 110.0,
        stock: 2,
        sku: "PRN-BOT-SET3-OAK",
      },
    ],
    specs: [
      { label: "Paper", value: "100% Cotton Fine Art Rag Paper 300gsm" },
    ],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: "p-105",
    title: "Minimalist Brass Table Lamp",
    subtitle: "Warm Sculptural Ambient Lighting with Dimmer",
    category: "Home Accent",
    price: 165.0,
    originalPrice: 190.0,
    rating: 4.9,
    reviewCount: 38,
    stock: 9,
    sku: "LMP-WOD-0165",
    description: "Hand-finished spun brass table lamp with warm LED illumination and touch dimmer dial.",
    vendorName: "Tahleel Studio",
    vendorPhone: "+15552345678",
    vendorEmail: "studio@altrio.com",
    vendorLocation: "San Francisco, CA",
    shippingInfo: "Ships within 48 hours.",
    returnPolicy: "30-Day Money Back.",
    media: [
      {
        id: "m1",
        type: "image",
        url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80",
        thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=200&q=80",
        alt: "Brass Lamp Display",
      },
    ],
    variants: [
      {
        id: "v-brass-standard",
        name: "Standard 16\" Height / Antique Brass",
        size: "16\" Height",
        color: "Antique Brass",
        price: 165.0,
        stock: 9,
        sku: "LMP-BRS-16",
      },
    ],
    specs: [
      { label: "Bulb Type", value: "Warm LED G9 (Included)" },
    ],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: "p-106",
    title: "Bohemian Hand-Woven Textile Wall Hanging",
    subtitle: "100% Organic Merino Wool & Cotton Fiber Art",
    category: "Wall Art & Canvas",
    price: 95.0,
    originalPrice: 120.0,
    rating: 4.8,
    reviewCount: 21,
    stock: 0,
    sku: "TAP-BOH-0095",
    description: "Intricately hand-knotted macramé tapestry crafted from unbleached organic cotton and hand-dyed merino wool.",
    vendorName: "Tahleel Studio",
    vendorPhone: "+15552345678",
    vendorEmail: "studio@altrio.com",
    vendorLocation: "San Francisco, CA",
    shippingInfo: "Ships in eco-friendly tubes.",
    returnPolicy: "30-Day Returns.",
    media: [
      {
        id: "m1",
        type: "image",
        url: "https://images.unsplash.com/photo-1584589167171-541ce45f1eea?auto=format&fit=crop&w=1200&q=80",
        thumbnail: "https://images.unsplash.com/photo-1584589167171-541ce45f1eea?auto=format&fit=crop&w=200&q=80",
        alt: "Textile Tapestry Display",
      },
    ],
    variants: [
      {
        id: "v-tapestry-natural",
        name: "20x32 Inches / Natural Cream & Terracotta",
        size: "20x32 Inches",
        color: "Natural Cream & Terracotta",
        price: 95.0,
        stock: 0,
        sku: "TAP-MAC-2032",
      },
    ],
    specs: [
      { label: "Fiber", value: "100% Organic Merino Wool & Unbleached Cotton" },
    ],
    reviews: [],
    relatedProducts: [],
  },
];

export function getProductById(id: string): Product {
  const found = SAMPLE_PRODUCTS.find(
    (p) => p.id.toLowerCase() === id.trim().toLowerCase()
  );
  return found || SAMPLE_PRODUCTS[0];
}
